### BT Dataset management

From the full BT dataset we have to clean the data in order to get the following characteristics:

    -Only one row per SN. (full SN required)
    
    -¿Keep the last "pass" test of each drawer?.
    
    -Not null data.

In [1]:
#Import:
import numpy as np
import pandas as pd

In [10]:
bt_df = pd.read_csv('../Data/BT_Report.csv')

In [11]:
bt_df.head()

,ID,SN,TEST,DAY,@TIME,TESTVERSION,STATUS,FIRST,LAST,SHIFT,...,RESULTNUM24,X24,RESULTNUM25,X25,RESULTNUM26,X26,RESULTNUM27,X27,RESULTNUM28,X28
0,1,DRW371702111,BT_914mm_NewBT,20170915,171553,6,F,Y,Y,1,...,BTRearSmallError_20N,-1.7,BTRearSmallError_15N,0.0,BTRearSmallError_30N,5.0,AccBTRearSmallError_25N,-8.2,DecBTRearSmallError_30N,-4.8
1,2,DRW371702111,BT_914mm_NewBT,20170915,172743,6,F,Y,Y,1,...,BTRearSmallError_20N,-1.7,BTRearSmallError_15N,0.0,BTRearSmallError_30N,5.0,AccBTRearSmallError_25N,-8.2,DecBTRearSmallError_30N,-4.8
2,3,DRW371702111,BT_914mm_NewBT,20170915,172931,6,F,Y,Y,1,...,BTRearSmallError_20N,-1.7,BTRearSmallError_15N,0.0,BTRearSmallError_30N,5.0,AccBTRearSmallError_25N,-8.2,DecBTRearSmallError_30N,-4.8
3,7,DRW371702111,BT_914mm_NewBT,20170921,114255,6,F,Y,Y,1,...,BTRearSmallError_20N,NaN,BTRearSmallError_15N,NaN,BTRearSmallError_30N,NaN,AccBTRearSmallError_25N,NaN,DecBTRearSmallError_30N,NaN
4,8,DRW371702111,BT_914mm_NewBT,20170921,114719,6,F,Y,Y,1,...,BTRearSmallError_20N,NaN,BTRearSmallError_15N,NaN,BTRearSmallError_30N,NaN,AccBTRearSmallError_25N,NaN,DecBTRearSmallError_30N,NaN

In [12]:
bt_df.shape

(5022, 69)

In [13]:
bt_df.columns

Index(['ID', 'SN', 'TEST', 'DAY', '@TIME', 'TESTVERSION', 'STATUS', 'FIRST',
       'LAST', 'SHIFT', 'FAMILY', 'Calibration', '@TABLE', 'RESULTNUM1', 'X1',
       'RESULTNUM2', 'X2', 'RESULTNUM3', 'X3', 'RESULTNUM4', 'X4',
       'RESULTNUM5', 'X5', 'RESULTNUM6', 'X6', 'RESULTNUM7', 'X7',
       'RESULTNUM8', 'X8', 'RESULTNUM9', 'X9', 'RESULTNUM10', 'X10',
       'RESULTNUM11', 'X11', 'RESULTNUM12', 'X12', 'RESULTNUM13', 'X13',
       'RESULTNUM14', 'X14', 'RESULTNUM15', 'X15', 'RESULTNUM16', 'X16',
       'RESULTNUM17', 'X17', 'RESULTNUM18', 'X18', 'RESULTNUM19', 'X19',
       'RESULTNUM20', 'X20', 'RESULTNUM21', 'X21', 'RESULTNUM22', 'X22',
       'RESULTNUM23', 'X23', 'RESULTNUM24', 'X24', 'RESULTNUM25', 'X25',
       'RESULTNUM26', 'X26', 'RESULTNUM27', 'X27', 'RESULTNUM28', 'X28'],
      dtype='object')

In [14]:
#deleting the ID column:.

bt_df = bt_df.drop("ID", axis = 1)

#We delete all the RESULTNUM columns:
import re

columns = bt_df.columns
for col in columns:
    if re.match(r'^RESULTN', col):
        bt_df.drop(col, axis=1, inplace=True)

In [15]:
#Renaming all the columns:
bt_columns = ['SN','TEST','day','time','TESTVERSION','status','FIRST','LAST','SHIFT',
             'FAMILY','Calibration','@TABLE','RADIUS_FRONT_BIG_ROLL','BTFrontBigError_25N',
              'BTFrontBigError_20N','BTFrontBigError_15N','BTFrontBigError_30N',
             'AccBTFrontBigError_25N','DecBTFrontBigError_30N','RADIUS_FRONT_SMALL_ROLL',
             'BTFrontSmallError_25N','BTFrontSmallError_20N','BTFrontSmallError_15N',
             'BTFrontSmallError_30N','AccBTFrontSmallError_25N','DecBTFrontSmallError_30N',
             'RADIUS_REAR_BIG_ROLL','BTRearBigError_25N','BTBTRearBigError_20N',
             'BTBTRearBigError_15N','BTBTRearBigError_30N','AccBTRearBigError_25N',
             'DecBTRearBigError_30N','RADIUS_REAR_SMALL_ROLL','BTRearSmallError_25N',
             'BTRearSmallError_20N','BTRearSmallError_15N','BTRearSmallError_30N',
             'AccBTRearSmallError_25N','DecBTRearSmallError_30N']
bt_df.columns = bt_columns
bt_df.head()

,SN,TEST,day,time,TESTVERSION,status,FIRST,LAST,SHIFT,FAMILY,...,BTBTRearBigError_30N,AccBTRearBigError_25N,DecBTRearBigError_30N,RADIUS_REAR_SMALL_ROLL,BTRearSmallError_25N,BTRearSmallError_20N,BTRearSmallError_15N,BTRearSmallError_30N,AccBTRearSmallError_25N,DecBTRearSmallError_30N
0,DRW371702111,BT_914mm_NewBT,20170915,171553,6,F,Y,Y,1,NIAGARA,...,24.5,35.1,6.5,63.5,1.4,-1.7,0.0,5.0,-8.2,-4.8
1,DRW371702111,BT_914mm_NewBT,20170915,172743,6,F,Y,Y,1,NIAGARA,...,46.6,6.9,31.0,63.5,1.4,-1.7,0.0,5.0,-8.2,-4.8
2,DRW371702111,BT_914mm_NewBT,20170915,172931,6,F,Y,Y,1,NIAGARA,...,47.4,13.1,27.1,63.5,1.4,-1.7,0.0,5.0,-8.2,-4.8
3,DRW371702111,BT_914mm_NewBT,20170921,114255,6,F,Y,Y,1,NIAGARA,...,47.4,13.1,27.1,72.5,NaN,NaN,NaN,NaN,NaN,NaN
4,DRW371702111,BT_914mm_NewBT,20170921,114719,6,F,Y,Y,1,NIAGARA,...,47.4,13.1,27.1,72.5,NaN,NaN,NaN,NaN,NaN,NaN

### Cleaning dataset

Columns TESTVERSION, FIRST, LAST, SHIFT, FAMILY, FAMILY, Calibreation, @TABLE are not relevant for the analysis.

In [16]:
#Deleting the not useful columns:

drop_columns2 = ['TEST','TESTVERSION','FIRST','LAST','SHIFT','FAMILY','Calibration','@TABLE']
bt_df.drop(drop_columns2, axis=1, inplace=True)

In [17]:
#SN has a format that is DRWXXXXXXXXX. We remove rows with other SN:

bt_df = bt_df[bt_df.SN != 'DRW']

We must unify the DAY and TIME column into a datetime column to filter each SN by the last test:

In [18]:
#We create a datetime column that concatenate both day and time columns into only one:
#The column time we ensure to have 6 elements adding a 0 in case it didn't.
# convert_time = lambda x: str(x) if len(str(x))==6 else ('0' + str(x))

def convert_time(x):
    while len(str(x)) < 6:
        x = '0' + str(x)
    return str(x)

bt_df['datetime'] = bt_df['day'].map(str) + bt_df['time'].apply(convert_time)
bt_df['datetime'] = pd.to_numeric(bt_df['datetime'])

In [19]:
#We reorder the columns:

bt_df = bt_df[['SN','day','time','datetime','status','RADIUS_FRONT_BIG_ROLL','BTFrontBigError_25N',
              'BTFrontBigError_20N','BTFrontBigError_15N','BTFrontBigError_30N',
             'AccBTFrontBigError_25N','DecBTFrontBigError_30N','RADIUS_FRONT_SMALL_ROLL',
             'BTFrontSmallError_25N','BTFrontSmallError_20N','BTFrontSmallError_15N',
             'BTFrontSmallError_30N','AccBTFrontSmallError_25N','DecBTFrontSmallError_30N',
             'RADIUS_REAR_BIG_ROLL','BTRearBigError_25N','BTBTRearBigError_20N',
             'BTBTRearBigError_15N','BTBTRearBigError_30N','AccBTRearBigError_25N',
             'DecBTRearBigError_30N','RADIUS_REAR_SMALL_ROLL','BTRearSmallError_25N',
             'BTRearSmallError_20N','BTRearSmallError_15N','BTRearSmallError_30N',
             'AccBTRearSmallError_25N','DecBTRearSmallError_30N']]

In [20]:
#We check the nulls in the dataframe:
bt_df.isna().sum()

SN                            0
day                           0
time                          0
datetime                      0
status                        0
RADIUS_FRONT_BIG_ROLL         0
BTFrontBigError_25N          16
BTFrontBigError_20N          16
BTFrontBigError_15N          16
BTFrontBigError_30N          16
AccBTFrontBigError_25N       36
DecBTFrontBigError_30N       29
RADIUS_FRONT_SMALL_ROLL       0
BTFrontSmallError_25N         0
BTFrontSmallError_20N         0
BTFrontSmallError_15N         0
BTFrontSmallError_30N         0
AccBTFrontSmallError_25N     49
DecBTFrontSmallError_30N     32
RADIUS_REAR_BIG_ROLL          0
BTRearBigError_25N           84
BTBTRearBigError_20N         84
BTBTRearBigError_15N         84
BTBTRearBigError_30N         84
AccBTRearBigError_25N       163
DecBTRearBigError_30N       133
RADIUS_REAR_SMALL_ROLL        0
BTRearSmallError_25N         54
BTRearSmallError_20N         54
BTRearSmallError_15N         54
BTRearSmallError_30N         54
AccBTRearSmallError_25N     169
DecBTRearSmallError_30N     143
dtype: int64

In [21]:
bt_df[bt_df.status=='P'].isna().sum()

SN                          0
day                         0
time                        0
datetime                    0
status                      0
RADIUS_FRONT_BIG_ROLL       0
BTFrontBigError_25N         0
BTFrontBigError_20N         0
BTFrontBigError_15N         0
BTFrontBigError_30N         0
AccBTFrontBigError_25N      0
DecBTFrontBigError_30N      0
RADIUS_FRONT_SMALL_ROLL     0
BTFrontSmallError_25N       0
BTFrontSmallError_20N       0
BTFrontSmallError_15N       0
BTFrontSmallError_30N       0
AccBTFrontSmallError_25N    0
DecBTFrontSmallError_30N    0
RADIUS_REAR_BIG_ROLL        0
BTRearBigError_25N          0
BTBTRearBigError_20N        0
BTBTRearBigError_15N        0
BTBTRearBigError_30N        0
AccBTRearBigError_25N       0
DecBTRearBigError_30N       0
RADIUS_REAR_SMALL_ROLL      0
BTRearSmallError_25N        0
BTRearSmallError_20N        0
BTRearSmallError_15N        0
BTRearSmallError_30N        0
AccBTRearSmallError_25N     0
DecBTRearSmallError_30N     0
dtype: int64

In [22]:
bt_df.status.value_counts()

P    3329
F    1693
Name: status, dtype: int64

The test columns are divided in two: test name and test result. We delete the first ones and rename the second ones.

In [23]:
#Groupby SN and select last test
#https://stackoverflow.com/questions/41525911/group-by-pandas-dataframe-and-select-latest-in-each-group

bt_df = bt_df.sort_values('datetime').groupby('SN').tail(1)

bt_df.head()

,SN,day,time,datetime,status,RADIUS_FRONT_BIG_ROLL,BTFrontBigError_25N,BTFrontBigError_20N,BTFrontBigError_15N,BTFrontBigError_30N,...,BTBTRearBigError_30N,AccBTRearBigError_25N,DecBTRearBigError_30N,RADIUS_REAR_SMALL_ROLL,BTRearSmallError_25N,BTRearSmallError_20N,BTRearSmallError_15N,BTRearSmallError_30N,AccBTRearSmallError_25N,DecBTRearSmallError_30N
12,DRW371702111,20170921,141543,20170921141543,F,68.0,19.8,17.0,17.8,19.7,...,47.6,26.5,33.3,61.6,54.6,57.3,72.2,51.8,16.6,41.4
33,DRW381700121,20170926,151104,20170926151104,P,77.3,12.8,14.3,17.3,20.5,...,16.6,4.7,7.4,50.1,0.2,0.6,19.0,10.2,-3.4,7.6
34,DRW391700001,20170926,160345,20170926160345,P,73.7,16.7,15.1,15.1,14.9,...,5.5,5.0,-0.8,67.6,11.6,9.9,28.3,15.6,2.9,9.5
35,DRW391700041,20170926,175024,20170926175024,P,71.9,15.9,14.1,22.3,14.0,...,17.7,3.3,12.1,63.3,17.5,21.2,13.0,23.8,7.4,14.1
43,DRW391700031,20170927,183026,20170927183026,P,78.8,-5.9,-16.0,-7.9,-3.4,...,20.0,15.6,11.8,64.8,11.6,1.2,13.0,16.7,-10.6,12.8

In [24]:
bt_df.status.value_counts()

P    2921
F     602
Name: status, dtype: int64

In [25]:
bt_df.to_csv('../Data/BT2.csv', index=False)